### ISSUE TITLE
Use sbt-jmh for benchmarking

### ISSUE THREAD

**Issue by dandxy89** [picnicml/doddle-benchmark#2]
Better benchmarking of the library.

Use ```sbt-jmh``` to benchmark and visualise the performance.

This was a recommendation from a [plokhotnyuk](https://www.reddit.com/user/plokhotnyuk)

**Comment by inejc** [comment]
Thanks for opening the issue.

**Comment by dandxy89** [comment]
Happy to pick this one up. Will look into the file locations issue too

**Comment by inejc** [comment]
That's great, give me a shout if you need any info.

**Comment by dandxy89** [comment]
In progess...
